sudo: required
services:
  - docker
node_js:
  - "10.15.3"
before_install:
  - docker build -t dideex/docker-react -f Dockerfile.dev .
script:
  - docker run dideex/docker-react npm run test -- --coverage